# AQQBot 配置文件
# 可使用 /aqqbot reload 重载

## 配置文件版本, 请勿修改!!!
version: 22

# 存储相关配置 (重启后生效)
storage:
  # 存储方式
  # 可选方式: file, sqlite, mysql
  type: "file"

  # SQLite 数据库配置
  sqlite:
    file: "aqqbot.db"

  # MySQL 数据库配置
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "123456"
    database: "aqqbot"

# 添加白名单
whitelist:
  # 是否启用该功能
  enable: true

  # 是否必须绑定后才能进入游戏
  # ! 若关闭该功能, 则 VERIFY_CODE 的验证方法不起效
  need_bind_to_login: true

  # 验证方法
  # - GROUP_NAME: 在QQ群中发送 $command $name 来给自己的QQ绑定指定的游戏账户(名称)
  # - VERIFY_CODE: 玩家在进入游戏后获取一个6位数验证码, 在QQ群发送 $command $code 后方可绑定游戏账户(名称)
  verify_method: "GROUP_NAME"

  # 验证码过期时间 (单位: 秒)
  # 在验证方法为 VERIFY_CODE 时可用
  verify_code_expire_time: 300

  # 一个QQ号最多可以绑定多少个账户
  max_bind_count: 1

  # 名称验证规则
  # 默认规则为支持任意字符
  name_rule: "[\\S]*"

  # 功能指令前缀
  prefix:
    # 绑定指令前缀
    # 用户需要发送的消息: $command $name
    # ! 如果验证方法为 VERIFY_CODE, 则用户需要发送的消息为: $command $code
    bind:
      - "/绑定"
      - "/bind"

    # 解绑指令前缀
    # 用户需要发送的消息: $command $name
    unbind:
      - "/解绑"
      - "/unbind"

  # 是否开启退群自动解绑
  unbind_on_leave: true

  # 可以无需绑定即可进入的用户所需要的权限:
  bypass_permission: "aqqbot.whitelist.bypass"

  # 使用非管理员命令的用户的冷却时间 (单位: 秒)
  cooldown:
    # 绑定指令的冷却时间
    bind: 60

    # 解绑指令的冷却时间
    unbind: 86400

  # 绑定后修改群名称
  # * 该功能要求 QQ 机器人有群管理员权限
  change_nickname_on_bind:
    # 是否启用该功能
    enable: false

    # 修改群昵称的格式
    # 可用变量: ${playerName} -> 游戏名, ${qq} -> QQ号, ${nickName} -> 当前用户群昵称
    format: "[${nickName}] ${playerName}"

  # 管理员管理
  admin:
    # 是否启用该功能
    enable: true

    # 绑定指令前缀
    # 用户需要发送的消息: $command $userId $name
    # ! 如果验证方法为 VERIFY_CODE, 则用户需要发送的消息为: $command $code
    bind:
      - "/管理绑定"
      - "/abind"

    # 解绑指令前缀
    # 用户需要发送的消息: $command $userId $name
    unbind:
      - "/管理解绑"
      - "/aunbind"


# 查询服务器基本信息
information:
  # 功能: 查询服务器在线玩家 输出结果:
  # 服务器在线玩家(${amount}): ${player_list}
  list:
    # 是否启用该功能
    enable: true

    # 获取指令
    command:
      - "/list"
      - "list"
      - "在线玩家"
      - "/在线玩家"
      - "服务器在线玩家"
      - "/服务器在线玩家"

  # 功能: @某人
  at:
    # 是否启用该功能
    enable: true

    # @人所需要包含的内容 (${player} 代表 @ 的玩家名)
    command:
      - "@${player}"
      - "${player}"

    # 在 @某人 后的操作
    action:
      - 'playsound block.bell.use master ${player}'
      - 'title @a subtitle {"text":"[AQQBot] ${userId} @了你!","color":"gold"}'

# 聊天(群服互联)功能
# * Velocity类服务端兼容性可能不是很好
chat:
  # 最大转发字数 (多余的会被替换为...)
  max_forward_length: 200

  # 群->服聊天转发功能 转发结果:
  # [QQ群(${groupId})] ${sender}: ${message}
  group_to_server:
    # 是否启用该功能
    enable: true

    # 若转发, 需要发送什么作为前缀的消息 (空代表不需要前缀)
    prefix:
      - ""

    # (仅Velocity可用!!!!!) 是否将消息发送到所有子服
    # ! 若不开启, 则不会发送消息到任何服务器
    vc_broadcast: false

    # 特定格式化 不需要开启上面的格式化消息选项即可使用
    # 使用方式: 使用 $filter:{内容} 代表匹配指定内容 使用 $regex:{正则表达式} 代表使用正则表达式匹配内容
    # 使用 $url:{屏蔽词json文件地址} $path:{在json文件内词库列表对应的路径} 代表通过URL地址获取屏蔽词 (如不填写path, 则默认为words)
    # 然后打一个空格 写 $replaceTo:{替换内容} 代表将匹配到的内容替换为指定内容 如果直接替换为空可不填写该项
    # 如果你不想替换内容而是取消消息发送, 请将 replaceTo 的内容改为 !CANCEL 即可
    # 不支持在内容 正则表达式或替换内容种出现空格, 如需出现请用 [[space]] 代替
    # 如: $filter:{§x} $replaceTo:{} 代表将所有 §x 符号替换成空字符 (即将所有 §x 符号去除)
    # 如: $regex:{\d{11}} $replaceTo:{电话号码} 代表将所有11位数字替换成 电话号码
    # 如: $url:{http://localhost:8080/test.json} $path:{filter} $replaceTo:{\"[[space]]屏蔽词[[space]]\"}
    #     代表将所有在test.json内filter的列表里的屏蔽词替换为 " 屏蔽词 "
    filter:
      - ""

  # 服->群聊天转发功能 转发结果:
  # [服务器] ${sender}: ${message}
  server_to_group:
    # 是否启用该功能
    enable: true

    # 若转发, 需要发送什么作为前缀的消息 (空代表不需要前缀)
    prefix:
      - ""

    # 是否格式化消息 (将颜色符号去除)
    # 默认包含 §0, §1 , ... , §9, §a, ..., §f, §k, §l, §m, §n, §o, §r
    default_format: true

    # 特定格式化 不需要开启上面的格式化消息选项即可使用
    # 使用方式: 使用 $filter:{内容} 代表匹配指定内容 使用 $regex:{正则表达式} 代表使用正则表达式匹配内容
    # 使用 $url:{屏蔽词json文件地址} $path:{在json文件内词库列表对应的路径} 代表通过URL地址获取屏蔽词 (如不填写path, 则默认为words)
    # 然后打一个空格 写 $replaceTo:{替换内容} 代表将匹配到的内容替换为指定内容 如果直接替换为空可不填写该项
    # 如果你不想替换内容而是取消消息发送, 请将 replaceTo 的内容改为 !CANCEL 即可
    # 不支持在内容 正则表达式或替换内容种出现空格, 如需出现请用 [[space]] 代替
    # 如: $filter:{§x} $replaceTo:{} 代表将所有 §x 符号替换成空字符 (即将所有 §x 符号去除)
    # 如: $regex:{\d{11}} $replaceTo:{电话号码} 代表将所有11位数字替换成 电话号码
    # 如: $url:{http://localhost:8080/test.json} $path:{filter} $replaceTo:{[[space]]屏蔽词[[space]]}
    #     代表将所有在test.json内filter的列表里的屏蔽词替换为 屏蔽词
    filter:
      - ""
#      - "$url:{https://ghproxy.net/https://raw.githubusercontent.com/alazeprt/AQQBot-Docs/master/fucker/database.json} $path:{words} $replaceTo:{***}" # 脏话词库

# 有关服务器的通知
notify:
  # 服务器启停通知
  server_status:
    # 是否开启该功能
    enable: true

    # 开启时发送的消息:
    start: "[AQQBot] XXX服务器已启动!"

    # 关闭时发送的消息:
    stop: "[AQQBot] XXX服务器已关闭!"

  # 玩家进出通知 (若玩家未绑定账号, 则会将userId这一参数设为 -1)
  player_status:
    # 是否开启该功能
    enable: true

    # 进入时发送的消息:
    join: "[AQQBot] ${playerName}(${userId}) 进入了服务器!"

    # 离开时发送的消息:
    leave: "[AQQBot] ${playerName}(${userId}) 离开了服务器!"

  # 玩家死亡通知
  player_death:
    # 是否开启该功能
    enable: true

    # 发送的消息:
    message: "[AQQBot] ${playerName}(${userId}) 因 ${deathMessage} 死亡了!"

# 服务器命令远程执行
# * 该功能仅支持Bukkit类服务端
# 通过在QQ发送指定前缀消息来执行服务器命令
# 执行命令时, 不需要再加 / 号, 只需要填写命令前缀
# 如: 在游戏里执行 /spark health -> 在QQ群内执行 /sudo spark health
command_execution:
  # 是否启用该功能
  enable: true

  # 允许使用该功能的人
  # $ADMIN 代表所有管理员
  # $OWNER 代表群主
  # $USER 代表所有用户
  # 范围覆盖: $USER > $ADMIN > $OWNER
  # 如果你想指定除了这里的人以外的特定用户, 你可填写用户的QQ号到这里
  allow:
    - "$ADMIN"

  # 指令前缀
  prefix:
    - "/sudo"
    - "/执行"

  # 执行命令的方案排序
  # 越前的越优先测试 若无法使用则会继续进行下一个测试 直到成功或全部测试失败
  # 可用方案:
  # - NATIVE: 通过 Bukkit 内部 API 内部方法创建 CommandSender 执行命令 (适用于高版本/非混合端)
  # - DEDICATED_SERVER: 通过 Bukkit 内部 API 获取 DedicatedServer 实例并以其执行命令 (适用于较高版本/非混合端)
  # - MINECRAFT_SERVER: 通过 Bukkit 内部 API 获取 MinecraftServer 实例并创建 RCON 实例以其执行命令 (适用于较低版本/部分混合端)
  # - SIMULATE_CONSOLE: 创建一个基于 Bukkit 外部 API 的 CommandConsoleSender 终端实例并执行命令 (适用于全版本/混合端)
  sort:
    - "NATIVE"
    - "DEDICATED_SERVER"
    - "MINECRAFT_SERVER"
    - "SIMULATE_CONSOLE"

  # 是否格式化消息 (将颜色符号去除)
  # 默认包含 §0, §1 , ... , §9, §a, ..., §f, §k, §l, §m, §n, §o, §r
  format: true

  # 特定格式化 不需要开启上面的格式化消息选项即可使用
  # 使用方式: 使用 $filter:{内容} 代表匹配指定内容 使用 $regex:{正则表达式} 代表使用正则表达式匹配内容
  # 使用 $url:{屏蔽词json文件地址} $path:{在json文件内词库列表对应的路径} 代表通过URL地址获取屏蔽词 (如不填写path, 则默认为words)
  # 然后打一个空格 写 $replaceTo:{替换内容} 代表将匹配到的内容替换为指定内容 如果直接替换为空可不填写该项
  # 不支持在内容 正则表达式或替换内容种出现空格, 如需出现请用 [[space]] 代替
  # 如: $filter:{§x} $replaceTo:{} 代表将所有 §x 符号替换成空字符 (即将所有 §x 符号去除)
  # 如: $regex:{\d{11}} $replaceTo:{电话号码} 代表将所有11位数字替换成 电话号码
  # 如: $url:{http://localhost:8080/test.json} $path:{filter} $replaceTo:{\"[[space]]屏蔽词[[space]]\"}
  #     代表将所有在test.json内filter的列表里的屏蔽词替换为 " 屏蔽词 "
  filter:
    - ""

  # 等待输出结果多长时间
  # 单位: 秒
  delay: 2

# Webhook 相关功能 (远程 WebSocket 服务器)
webhook:
  # 是否启用该功能
  enable: false

  # 远程 WebSocket 服务器地址
  host: "0.0.0.0"

  # 远程 WebSocket 服务器端口
  port: 8080

  # 远程 WebSocket 服务器 Token
  # ! 务必修改, 切忌泄露
  token: "type_your_token_here"

  # 服务器的名称
  # 请自行修改
  name: "A Minecraft Server"

  # 服务器的 UUID (唯一标识符)
  # 会自动生成, 切忌修改!
  server_uuid: ""

# 调试选项
debug:
  # 是否启用该功能
  # ! 该项启用后才能使用调试选项的子功能 (如logger)
  enable: false

  # 有关日志的调试选项
  logger:
    # 是否启用该功能
    enable: true

    # 日志存储文件名
    file: "debug.log"

    # 每隔多长时间保存一次日志文件 (单位: 秒)
    # 设置为 -1 代表关服时保存
    # 设置为 0 代表实时保存 (在有新的日志时就保存)
    save_interval: 0
