# .github/workflows/build.yml
name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build Nuxt project
      run: yarn build
      
    - name: Download Node.js distributions
      run: |
        # 下载 Windows Node.js
        curl -L -o node-win-x64.zip https://nodejs.org/dist/v22.18.0/node-v22.18.0-win-x64.zip
        
        # 下载 Linux Node.js
        curl -L -o node-linux-x64.tar.xz https://nodejs.org/dist/v22.18.0/node-v22.18.0-linux-x64.tar.xz
        
    - name: Prepare package structures
      run: |
        # 创建三个目标目录结构
        mkdir -p package/AQBManager-win
        mkdir -p package/AQBManager-linux
        mkdir -p package/AQBManager-noenv
        
        # 复制构建输出到所有三个目录
        for dir in package/AQBManager-win package/AQBManager-linux package/AQBManager-noenv; do
          if [ -d ".output" ]; then
            cp -r .output "$dir"/
          else
            echo "Warning: .output directory not found"
          fi
        done
        
        # 复制 script 目录内容到所有三个目录的根目录
        for dir in package/AQBManager-win package/AQBManager-linux package/AQBManager-noenv; do
          if [ -d "script" ]; then
            cp -r script/* "$dir"/ 2>/dev/null || echo "No files to copy from script directory"
          else
            echo "Warning: script directory not found"
          fi
        done
        
        # 解压 Windows Node.js 到 win 版本目录
        unzip node-win-x64.zip -d package/AQBManager-win/
        # 重命名为标准名称
        WINDOWS_DIR=$(find package/AQBManager-win -maxdepth 1 -type d -name "*win-x64" | head -1)
        if [ -n "$WINDOWS_DIR" ] && [ "$WINDOWS_DIR" != "package/AQBManager-win/node-v22.18.0-win-x64" ]; then
          mv "$WINDOWS_DIR" package/AQBManager-win/node-v22.18.0-win-x64
        fi
        
        # 解压 Linux Node.js 到 linux 版本目录
        tar -xJf node-linux-x64.tar.xz -C package/AQBManager-linux/
        # 重命名为标准名称
        LINUX_DIR=$(find package/AQBManager-linux -maxdepth 1 -type d -name "*linux-x64" | head -1)
        if [ -n "$LINUX_DIR" ] && [ "$LINUX_DIR" != "package/AQBManager-linux/node-v22.18.0-linux-x64" ]; then
          mv "$LINUX_DIR" package/AQBManager-linux/node-v22.18.0-linux-x64
        fi
        
        # 显示最终的目录结构
        echo "Final package structures:"
        echo "=== Windows version ==="
        find package/AQBManager-win -type f | head -20
        echo "=== Linux version ==="
        find package/AQBManager-linux -type f | head -20
        echo "=== No environment version ==="
        find package/AQBManager-noenv -type f | head -20
        
    - name: Create zip archives
      run: |
        cd package
        
        # 创建 Windows 版本压缩包
        zip -r ../AQBManager-win.zip AQBManager-win
        echo "Windows archive created successfully"
        echo "Windows archive size: $(du -h ../AQBManager-win.zip)"
        
        # 创建 Linux 版本压缩包
        zip -r ../AQBManager-linux.zip AQBManager-linux
        echo "Linux archive created successfully"
        echo "Linux archive size: $(du -h ../AQBManager-linux.zip)"
        
        # 创建无环境版本压缩包
        zip -r ../AQBManager-noenv.zip AQBManager-noenv
        echo "No environment archive created successfully"
        echo "No environment archive size: $(du -h ../AQBManager-noenv.zip)"
        
        cd ..
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: AQBManager-win
        path: AQBManager-win.zip
        retention-days: 30
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: AQBManager-linux
        path: AQBManager-linux.zip
        retention-days: 30
        
    - name: Upload No Environment artifact
      uses: actions/upload-artifact@v4
      with:
        name: AQBManager-noenv
        path: AQBManager-noenv.zip
        retention-days: 30
